### PR TITLE
fix: fix availability message and variant selectors

### PR DESCRIPTION
**Pull request by grzegorzpokorski**
Fix for #932 issue.

localhost_3000_products_polo-shirt-2
localhost_3000_products_polo-shirt-2_variant=UHJvZHVjdFZhcmlhbnQ6MjYx
localhost_3000_products_polo-shirt-2_variant=UHJvZHVjdFZhcmlhbnQ6MjYx (1)

### CODE REVIEW

**Comment by mmiszy** [comment]
Buttons for unavailable variants could be just disabled

**Comment by grzegorzpokorski** [comment]
> Buttons for unavailable variants could be just disabled

Should I provide some information for user why they are disabled or just simply disable them?

**Comment by timuric** [comment]
> OK, I get it 😂 I going to refactor this code to achieve result similar to this: Zrzut ekranu 2023-10-12 130115

@grzegorzpokorski email notifications for `back in stock` is a awesome, however this would be out of scope for starter kit. We only want to focus on functionality essential functionality of Saleor API to keep things lean and customizable to any project.

If you would like to contribute more specific use cases, you could create a dedicated repo or fork that we can promote to the community.

**Comment by mmiszy** [comment]
I'd not do the "email me when back in stock" thing but instead just disable the variants that are out of stock.
If all variants for given product are out of stock we can show additional notification.

**Comment by grzegorzpokorski** [comment]
I updated images in PR description.

**Review by mmiszy — APPROVED** [review]

**Pull request merged**
