### PR TITLE
fix(checkout): remove divider in SignIn sections and add vertical padding on Sign In button

### LINKED ISSUE #976: Fix padding
### Summary

Fix padding and remove bottom line 

image

### Steps to reproduce

1. Go to checkout
2. Sing in

### A link to a reproduction repository

_No response_

### Output from envinfo

_No response_

### PR DESCRIPTION
**Pull request by fitrahfm**
- Fix #976 issue by removing divider (horizontal line) and adding 1rem vertical padding on Sign In button

Screen Shot 2023-10-21 at 1 46 41 AM

### CODE REVIEW

**Comment by zaiste** [comment]
@fitrahfm please rebase and sign the CLA

**Comment by fitrahfm** [comment]
> @fitrahfm please rebase and sign the CLA

done

**Comment by mmiszy** [comment]
Build failed:

```
Failed to compile.
--
20:21:38.116 |  
20:21:38.116 | ./src/checkout/sections/SignIn/SignIn.tsx:81:43
20:21:38.117 | Type error: Cannot find name 'formatMessage'.
```

**Review by mmiszy — APPROVED** [review]

**Review by zaiste — APPROVED** [review]

**Comment by fitrahfm** [comment]
@mmiszy @zaiste is there anything I could help with this failed build?

**Pull request merged**
