### PR TITLE
feat: SEO optimization

### LINKED ISSUE #980: SEO optimization, add OG images and page titles
[] Product page should include product image and product SEO fields
`<title>{product.name} | {product.seoTitle}</title>`
`<meta name="description" content={product.seoDescription}/>`

[] Use description of Collections and categories
`<title>{collection.name} | {collection.seoTitle}</title>`
`<meta name="description" content={collection.seoDescription}/>`

[] Pages like account and Checkout should use [Name of the page] [Global title of the store]
`<title>Checkout | ACME store</title>`

### PR DESCRIPTION
**Pull request by samiralibabic**
Closes #980. Changed title to match format [Name of the page] [Global title of the store]

### CODE REVIEW

**Comment by mmiszy** [comment]
What's the status of this PR @samiralibabic ?

**Comment by samiralibabic** [comment]
> What's the status of this PR @samiralibabic ?

I'm waiting on some input. I've verified and titles, OG images and SEO metadata seem to be correct already (except the small change I made here). Do you have more info?

**Comment by samiralibabic** [comment]
> I think it would be great to change a og image for product page - product thumbnail would be a more appropriate for product page than default image provided for pages like a "home".
> 
> Also common practice is to provide a JSON-LD object which making it easier for search engines and other applications to understand the content and relationships within the data what also boost SEO - smth like that whould be enough for a product page:
> 
> ```json
> {
>   "@context": "http://schema.org",
>   "@type": "Product",
>   "name": "Product Name",
>   "description": "Product description goes here.",
>   "offers": {
>     "@type":"AggregateOffer",
>     "availability":"https://schema.org/InStock",
>     "priceCurrency":"USD",
>     "highPrice":"20.0",
>     "lowPrice":"15.0"
>   },
>   "image": "url-to-product-image.jpg",
> }
> ```

Should I add JSON-LD in this PR too, or does it require discussion?

**Comment by grzegorzpokorski** [comment]
> > I think it would be great to change a og image for product page - product thumbnail would be a more appropriate for product page than default image provided for pages like a "home".
> > Also common practice is to provide a JSON-LD object which making it easier for search engines and other applications to understand the content and relationships within the data what also boost SEO - smth like that whould be enough for a product page:
> > ```json
> > {
> >   "@context": "http://schema.org",
> >   "@type": "Product",
> >   "name": "Product Name",
> >   "description": "Product description goes here.",
> >   "offers": {
> >     "@type":"AggregateOffer",
> >     "availability":"https://schema.org/InStock",
> >     "priceCurrency":"USD",
> >     "highPrice":"20.0",
> >     "lowPrice":"15.0"
> >   },
> >   "image": "url-to-product-image.jpg",
> > }
> > ```
> 
> Should I add JSON-LD in this PR too, or does it require discussion?

Hi! I'm not the maintainer of this project, and I don't decide what should be implemented. However, I believe providing JSON-LD is a common industry practice. I also don't see any drawbacks to this feature, so it might be beneficial to include it in the project, expecially for product pages. In my view, it is related to SEO, so it could be introduced now or implemented later in a separate PR. Ultimately, the decision is up to you 🙂

**Review by mmiszy — APPROVED** [review]

**Pull request merged**
